### ISSUE TITLE
Further refining our definition of "Topic" and "Pathway"

### ISSUE THREAD

**Issue by chartgerink** [ubvu/open-handbook#113]
In order to be more precise in our requirements for topics and pathways, I am proposing more concrete and encompassing definitions to ensure they are consistent over time.

## Topic

A "Topic" is a specific thing, concept, entity, or category. Each "Topic" must be specific, a noun/[noun phrase](https://en.wikipedia.org/wiki/Noun_phrase), and distinct from existing topics.

<details>

Examples of "Topics" as noun phrases:
* Data Management Plan
* Climate Change
* Supply Chain Management

Noun phrases include any accompanying words that modify the main noun (e.g., "data management plan" where "plan" is the main noun and "data management" is the modifier).

</details>

## Pathway

A Pathway is a structured sequence of **curated topics** designed to guide an audience through a coherent exploration or learning process. Each Pathway is curated to ensure that the selected topics jointly build towards a specific **objective**, offering a **logical sequence** from one concept to the next. The Pathway may include **connective elements**—such as explanations, transitions, or summaries—that create a **cohesive experience** of the topics together, providing context and enhancing understanding. 

<details>

### Key Components of a Pathway:

1. **Curated Topics**: A collection of topics that are deliberately chosen to be part of the Pathway. Each topic is a key component of the overall learning or exploration objective.

2. **Logical Sequence**: The topics are arranged in a specific order that makes sense for the intended audience, allowing them to build knowledge or understanding progressively.

3. **Connective Elements**: Transitions, explanations, or summaries that link the topics together. These elements help clarify how each topic relates to the others and to the overall objective of the Pathway.

4. **Objective-Driven**: The Pathway is designed with a clear purpose, whether it’s to onboard new PhD candidates, introduce a new concept, or guide through a complex process.

5. **Cohesive Experience**: The entire Pathway is presented as a unified whole, with each part contributing to a comprehensive understanding of the subject matter.
</details>

<details>
<summary>Example</summary>

### Example:

**PhD Candidate Onboarding Pathway**: 

- **Objective**: To equip new PhD candidates with the essential knowledge and resources they need to succeed in their programs.
  
- **Topics**: 
- **Academic Research Fundamentals**: Introduction to the basics of conducting and evaluating research.
- **Data Management Plan**: Guidelines for organizing and handling research data.
- **Research Ethics**: Understanding ethical considerations and compliance in research.
- **Literature Review Techniques**: Strategies for conducting effective literature reviews.
- **Time Management Strategies**: Best practices for balancing research, coursework, and other responsibilities.
  
- **Connective Elements**: 
  - **Introduction**: A brief overview explaining the importance of each topic and how they interrelate.
  - **Transitions**: Short sections that explain why moving from one topic to the next is logical and beneficial.
  - **Summary**: A recap that ties all the topics together, reinforcing the overarching goal of successful PhD onboarding.

</details>

<details>
<summary>Alternative names for Pathway</summary>

1. **Roadmap**: Suggests a structured plan or guide that outlines the key topics in a specific order, much like a map guiding someone through a journey.
   
2. **Journey**: Conveys the idea of moving through different stages or topics, often used in educational or developmental contexts.

3. **Sequence**: A straightforward term that emphasizes the specific order in which topics are presented.

4. **Curriculum**: Often used in academic settings, this term implies a comprehensive set of topics or subjects arranged for a particular learning objective.

5. **Guide**: Implies a document or resource designed to help someone navigate through key topics or areas of interest.

6. **Framework**: Suggests a structured approach to covering topics, often used in professional or academic contexts.

7. **Blueprint**: Indicates a detailed plan or outline that provides a clear structure for the topics covered.

8. **Learning Path**: Similar to "Pathways," this term emphasizes a structured approach to learning specific topics in a particular order.

9. **Progression**: Implies a forward-moving sequence, ideal for presenting topics that build upon one another.

10. **Syllabus**: Typically used in educational contexts, this term refers to an outline or summary of topics covered in a course.

</details>

---

@Karvovskaya @Jolien-S @jhrudey @Elisa-on-GitHub what do you think of these?

**Comment by jhrudey** [comment]
I really like this concept and I think it's well defined. Regarding the terminology for pathway vs the other options, I think pathway works well, learning path is probably the best second alternative imo. Would the goal be to have the same information topics available (e.g. DMPs, research ethics etc) and then to reuse them in different pathways as needed?

Also where would be the best place to document these (and potentially other definitions) for reference in the future (since I'm not sure an issue is the best place to serve as a reference doc)?

**Comment by chartgerink** [comment]
@jhrudey thanks for the feedback 😊 

> Would the goal be to have the same information topics available (e.g. DMPs, research ethics etc) and then to reuse them in different pathways as needed?

Yes. The concept as implemented does not change in that sense. The main reason for providing alternative names is that we got the feedback from VU UX team that pathway is not immediately obvious if you've never heard it. So if we can find a more obvious name, that would help 👍 

> where would be the best place to document these (and potentially other definitions) for reference in the future (since I'm not sure an issue is the best place to serve as a reference doc)?

You are right – I will document this once we agree on the definition, most probably on the website itself.

**Comment by jhrudey** [comment]
Since VU UX said pathway is a bit confusing, perhaps learning path is the best option.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Chris Hartgerink ***@***.***>
Verzonden: Tuesday, August 27, 2024 1:12:24 PM
Aan: ubvu/open-handbook ***@***.***>
CC: Hrudey, E.J. (Jessica) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [ubvu/open-handbook] Further refining our definition of "Topic" and "Pathway" (Issue #113)


@jhrudey<https://github.com/jhrudey> thanks for the feedback 😊

Would the goal be to have the same information topics available (e.g. DMPs, research ethics etc) and then to reuse them in different pathways as needed?

Yes. The concept as implemented does not change in that sense. The main reason for providing alternative names is that we got the feedback from VU UX team that pathway is not immediately obvious if you've never heard it. So if we can find a more obvious name, that would help 👍

where would be the best place to document these (and potentially other definitions) for reference in the future (since I'm not sure an issue is the best place to serve as a reference doc)?

You are right – I will document this once we agree on the definition, most probably on the website itself.

**Comment by Karvovskaya** [comment]
Thanks for all the work, @chartgerink and @jhrudey 
I really like how the definitions are worked out. I was wondering if we maybe need to say something about the preferred size of a topic - how large is the building block we have in mind? I am also looking at the way topics are listed - we now have an alphabetic list with an empty "author" column under the menue topic. Do we need to say something about it?
Chris, I noticed that you suggest [Data Management Plan (DMP)](https://ubvu.github.io/open-handbook/topics/data-management-plan.html) as an example of a pathway - however at the moment it actually a topic, right? Do I interpret it right that we'll need to determine topics inside it?

**Comment by chartgerink** [comment]
> I was wondering if we maybe need to say something about the preferred size of a topic - how large is the building block we have in mind?

You are right – I am not sure what the best size recommendation is at this time. We could provide a generic topic structure to follow in case that is helpful, and recommend to keeping the topic as condensed as possible. This would allow us to practically keep things reduced to max 1 page. A generic structure could be:

- Definition
- Benefits

> I am also looking at the way topics are listed - we now have an alphabetic list with an empty "author" column under the menue topic. Do we need to say something about it?

This is a bit out of scope for this issue – continuing the discussion in #119.

> Chris, I noticed that you suggest [Data Management Plan (DMP)](https://ubvu.github.io/open-handbook/topics/data-management-plan.html) as an example of a pathway - however at the moment it actually a topic, right? Do I interpret it right that we'll need to determine topics inside it?

@Karvovskaya – maybe something got mixed up here? I see the DMP as a topic example and **as part of** the "PhD Candidate Onboarding" pathway. It should definitely not be its own pathway 👍

**Comment by Karvovskaya** [comment]
My bad, I misunderstood something. Indeed Data Management Plan is among topic examples.
I like "learning path" as an alternative. I also like "guide" because it intuitively feels as a collection of topics.

**Comment by Karvovskaya** [comment]
This is a bit of a random though but I want to add it here before I foreget. Is my interpretation of the example above correct that we could utilise the word "learning path" or "guide" to differentiate between pathways and topics? "PhD Candidate Onboarding Pathway" would be then "PhD Candidate Onboarding Learning Path" or "PhD Candidate Onboarding Guide"?

**Comment by chartgerink** [comment]
@Karvovskaya - this would become the name also in the menu bar. The example name is a bit confusing, sorry for that. If we would do it literally we would opt for consistency, yes.

**Comment by chartgerink** [comment]
Other suggestions from the 2nd hackathon:

- Approach
- Collection
- Section
- Overview
