### ISSUE TITLE
Proofread Topic "Persistent Identifier"

### ISSUE THREAD

**Issue by vansteph** [ubvu/open-handbook#123]
1. Does it contain a singular topic or multiple? 
 
- also contains information about Yoda / Yoda archiving functions. Maybe this topic can be linked to the Yoda topic / tools topic?

3. Does it clearly define the topic in the first paragraph?

- I would add the problem of link rot with URLs (to understand why picking up extra trouble) and that PIDs may be domain specific. PIDs allow researchers to receive recognition and rewards for their work as citation databases count mentions of PIDs, that may be a good motivation.

5. Is the topic page clear when read on its own?

- I think so.

**Comment by chartgerink** [comment]
Thanks @vansteph! 🙌 Added issue #195 to track the work on adding link rot. We are tracking the addition of Yoda as a topic as well in #92.

Proofreading like this is helpful in building confidence in the content – thank you for doing that 😊
