### ISSUE TITLE
Proofread Topic "Data Citation"

### ISSUE THREAD

**Issue by vansteph** [ubvu/open-handbook#128]
1. Does it contain a singular topic or multiple? 

- A singular topic, but if there would be a topic about "metadata quality" or "recognition and rewards", the topic would be related.

2. Does it clearly define the topic in the first paragraph?

- could clarify that a publication refers to a "text publication" " journal article etc in the first sentence
- maybe we could add a sentence about why citing data (e.g. to give and receive credit, to show the impact of data, to be visible in a knowledge / PID graph)
- clarify that the shape of the citation is mainly for human eyes, but that the PID has to be correct in order to be recognised for citation counts. 
- Add information about versions, always use the PID that refers directly to the version of the dataset used for the research (in Zenodo for example you have a PID for every version)

4. Is the topic page clear when read on its own?

- yes, it makes sense

Improvements could be:

- write hyperlinks in a way that they open in a new tab
- will software citations become a topic on its own or will it be part of this one?

**Comment by chartgerink** [comment]
Thank you @vansteph 🙌 I made some improvements based on your feedback in #196. 😊
