### ISSUE TITLE
Minimizing the use of VU Login walled pages

### ISSUE THREAD

**Issue by chartgerink** [ubvu/open-handbook#130]
LibGuide referred to a lot of login walled pages. Part of the migration ported that over too.

We want to try to reduce this as much as we can. 

- Where possible, we can instead link to the relevant topics. 
- If there are specific login walled links needed, we try to keep them limited to the topics, not the pathways.
- We can identify which URLs are likely to be login walled, and search through the handbook to double check all instances
- Where login walled links are needed, we want to provide some, clear indication that this is the case.

**Comment by Karvovskaya** [comment]
I have a problem with data-storage topic. @Elisa-on-GitHub you ordered it so nicely, it really looks great. But we have this problem that all the links are loginwalled to the service portal. 
There are no open university pages with more information. 
We need some unified solution. Something like this? "To request OneDrive, login at [Serviceportal](https://services.vu.nl/esc?id=emp_taxonomy_topic&topic_id=eed3d23e9785d950e553359fe153affc)  with VU credentials." 
What do you think, Elisa? Would it be enough to give context that login is required?

**Comment by Elisa-on-GitHub** [comment]
The LibGuides had actually solved this by using html code to create a little lock symbol to indicate that a link was walled. Maybe we can try something similar? I'll create a branch to experiment a little

**Comment by Elisa-on-GitHub** [comment]
The emoji don't seem to render correctly in the preview - @chartgerink do you know if this is a netlify thing or should I add them differently? I used [this list](https://gist.github.com/rxaviers/7360908)

**Comment by chartgerink** [comment]
@Elisa-on-GitHub thanks for trying this out! It seems like I had to enable support for this – it is fixed with #169. I like your proposition of not reinventing the wheel here.

Do we know what domains tend to lead to login walled pages? I can make this change fairly quickly in case we know the set of domains 😊

**Comment by chartgerink** [comment]
Documenting here, the links I could observe as leading to login walled pages:

- https://services.vu.nl
- https://vu.nl/en/employee

I will open up a PR to add the lock symbol in front of these URLs as a fix for this issue. If there are more URLs that have login walls, please mention so here, even if the issue is closed, and we can re-open 😊
