### ISSUE TITLE
Research Data Netherlands links

### ISSUE THREAD

**Issue by Alex-van-der-Jagt** [ubvu/open-handbook#136]
These seem to have gone, there is only a very general "datamanagement" section. Should we remove this or find a new source?

**Comment by chartgerink** [comment]
Do you mean this one in `document-and-preserve.qmd`?

> * Research Data Netherlands: [Data selection](https://datasupport.researchdata.nl/en/start-the-course/iv-harvest-phase/data-selection).

**Comment by Alex-van-der-Jagt** [comment]
I found two places, but any reference to this site should be reevaluated:
- https://ubvu.github.io/open-handbook/pathways/document-and-preserve.html#selecting-data-for-archiving
- https://ubvu.github.io/open-handbook/pathways/document-and-preserve.html#documenting-your-data

**Comment by chartgerink** [comment]
Thanks – will fix this week 😊
