### ISSUE TITLE
Codebook examples

### ISSUE THREAD

**Issue by Alex-van-der-Jagt** [ubvu/open-handbook#137]
Only one of the links still works. Are there any good places to find (openly published) codebooks which we can link to here (prefereably multiple diciplines). These should preferably have a DOI or other persistent identifier.

**Comment by chartgerink** [comment]
Thanks @Alex-van-der-Jagt – would you mind specifying where this is exactly? That will help identify what you are referring to 😊

**Comment by Alex-van-der-Jagt** [comment]
Of course. It is here: 
https://ubvu.github.io/open-handbook/pathways/document-and-preserve.html#codebooks

No idea why I forgot to mention where this is.

**Comment by chartgerink** [comment]
Thanks for adding 😊
