### ISSUE TITLE
Links for `emgo.nl` lead to unexpected website

### ISSUE THREAD

**Issue by chartgerink** [ubvu/open-handbook#157]
The links for `emgo.nl` lead to a website `enqueteplein` ("survey square").

I suspect this means the domain expired and somebody hijacked the traffic there. But before I move ahead and remove these links or adjust them, I would need confirmation this is indeed something that needs to be changed, and if so, whether it should be outright deletion or there is a likely place to find replacement URLs.

For example: https://github.com/ubvu/open-handbook/blob/31398c9e250cb14b5cd64c8b2f89fde835ed4731/guides/plan-and-design.qmd#L291

**Comment by chartgerink** [comment]
@Karvovskaya @Jolien-S @jhrudey @Elisa-on-GitHub

**Comment by Karvovskaya** [comment]
Probably @Jolien-S knows better the reasoning to reference these materials. From what I understand, this resource is now called APH Quality Handbook https://www.amsterdamumc.org/en/research/institutes/amsterdam-public-health/information/aph-quality-handbook.htm
In Data Cleaning section of LibGuide this link actually works https://aph-qualityhandbook.org/set-up-conduct/process-analyze-data/3-2-quantitative-research/3-2-1-data-processing/data-cleaning-and-transformation//
I am wondering if we should give some context here why we refer to Amsterdam Public Health? Or at least specify that this is relevant for health sciences?

**Comment by jhrudey** [comment]
Yeah EMGO hasn't existed for a while now and I imagine they probably didn't update the pages to redirect to the new name. EMGO was changed to Amsterdam Public Health and I imagine the EMGO pages that were linked were going to the EMGO quality handbook. So now those links can go to the APH Quality Handbook https://aph-qualityhandbook.org/. If you have a list of the broken links somewhere, I can see if I can find the correct pages for them on the APH website
