### ISSUE TITLE
Updated links request

### ISSUE THREAD

**Issue by chartgerink** [ubvu/open-handbook#170]
In #163, I observed some links that I could not fix myself.

Removed some links that may need to be replaced:

- [x] https://assets.vu.nl/d8b6f1f5-816c-005b-1dc1-e363dd7ce9a5/ae86a9d8-90a8-4d05-a924-4f6646a5351f/Informed_Consent_and_Information_Letter_Checklist_tcm263-917997.pdf
- [x] https://assets.vu.nl/d8b6f1f5-816c-005b-1dc1-e363dd7ce9a5/061ec9b1-f94f-47a7-81c4-099827ec4996/Werkproces%20meldplicht%20datalekken.pdf
- [x] https://assets.vu.nl/d8b6f1f5-816c-005b-1dc1-e363dd7ce9a5/ae86a9d8-90a8-4d05-a924-4f6646a5351f/Informed_Consent_and_Information_Letter_Checklist_tcm263-917997.pdf
- [x] DPIA template link
- [ ] #208
- [x] protocol reporting a data breach
- [x] PreDPIA tool

Can @Karvovskaya maybe provide copies of these files or new locations?

**Comment by Karvovskaya** [comment]
I will need to check these with @Elisa-on-GitHub ! I will try to do this on Monday 30 September

**Comment by Karvovskaya** [comment]
- [ ] https://assets.vu.nl/d8b6f1f5-816c-005b-1dc1-e363dd7ce9a5/ae86a9d8-90a8-4d05-a924-4f6646a5351f/Informed_Consent_and_Information_Letter_Checklist_tcm263-917997.pdf
@jhrudey, this document originally comes from your FAQ - the certificate has expired and we can't open it anymore. Could you please check if you have a version and if it's still relevant? Could we upload it here?
- [ ]  https://assets.vu.nl/d8b6f1f5-816c-005b-1dc1-e363dd7ce9a5/061ec9b1-f94f-47a7-81c4-099827ec4996/Werkproces%20meldplicht%20datalekken.pdf  this is the same as **protocol reporting a data breach** replace with https://vu.nl/en/employee/emergencies/data-leaks-and-other-incidents

- [ ]  DPIA template link - we can't put the link. I will add a text explaining that DPIA can only be done togehter with a privacy champion
- [ ]  PURE manual (EN + NL) For this one, we need to check with our colleagues working with PURE! @Elisa-on-GitHub promised to ask them
- [ ]  PreDPIA tool https://libguides.vu.nl/ld.php?content_id=34943732 does this work? This is an excel file from february 2021

**Comment by jhrudey** [comment]
The ICF checklist is found here https://assets-us-01.kc-usercontent.com/d8b6f1f5-816c-005b-1dc1-e363dd7ce9a5/ae86a9d8-90a8-4d05-a924-4f6646a5351f/Informed_Consent_and_Information_Letter_Checklist_tcm263-917997.pdf. I'm working on an html version to make linking easier, but had several things get in the way, so this is the best option for now. This link is found on this VUweb page https://vu.nl/en/employee/research-data-management-fbms/privacy-and-research-fgb so if it's wiser, you could also link to the VUweb page since that will not change (unless we get rid of VUweb)

**Comment by jhrudey** [comment]
Also regarding the pre-DPIA, I believe (but don't know for certain) that Tom and Martine want to move away from the pre-DPIA being available directly to the researchers and instead force the researchers into contact with the privacy champions. The pre-DPIA is no longer on this page https://vu.nl/en/employee/privacy-and-information-security/working-with-personal-data and on the 5-step privacy plan https://assets-us-01.kc-usercontent.com/d8b6f1f5-816c-005b-1dc1-e363dd7ce9a5/ad3de0e7-b935-471a-8d31-51c06ba47c88/Privacy%20five-step%20plan.pdf it simply states to get your pre-DPIA from your privacy champion.

**Comment by Karvovskaya** [comment]
Thanks, @jhrudey, good point about pre-DPIA. We will check with the privacy team. @chartgerink let's not include the pre-DPIA file for now!

**Comment by chartgerink** [comment]
Thanks! I will update the links after lunch 😊
