### ISSUE TITLE
Check titles for two topics that are now called 'Persistent identifier'

### ISSUE THREAD

**Issue by Jolien-S** [ubvu/open-handbook#175]
Two topics are now called 'Persistent identifier':

- https://ubvu.github.io/open-handbook/topics/persistent-identifier.html; I think this one is correctly titled
- https://ubvu.github.io/open-handbook/topics/data-publication.html; this one was originally (in LibGuide) titled 'Data publication'. 

The page on data publication used to contain a section 'What is a persistent identifier?' and this section is no longer part of the page in the Handbook. Maybe something got mixed up there?

I think for now https://ubvu.github.io/open-handbook/topics/data-publication.html should get the title 'Data publication'.

**Comment by chartgerink** [comment]
Thanks @Jolien-S 🙌

Something is going wrong here indeed - the topic Persistent Identifier is being copied over into the Data Publication one, which causes a heading conflict (that is, two titles and quarto picks the last occurrence).

I will update to link out to Persistent Identifier, as for now we should not be using include statements in topics (only in guides).
