### ISSUE TITLE
Proofread topic: Data storage

### ISSUE THREAD

**Issue by TMHofstra** [ubvu/open-handbook#178]
Does it contain a singular topic or multiple?

- You could argue that **sharing data** can be its own topic. It would be a very short topic, that loops back to Research Drive and YODA as well, though.

If it contains multiple, which ones?

- Data Storage
- Sharing Data (arguably, best to check with Elisa @Elisa-on-GitHub )

Does it clearly define the topic in the first paragraph?

- Yes. We can add that this page deals with Active Storage During A Research and that storage for when you're done is dealt by Archiving and Publishing.

Is the topic page clear when read on its own?

- Yes

**Comment by chartgerink** [comment]
Thanks @TMHofstra 🙌 

I was taking a look and "Data Storage" and "Data Sharing" seems like it could be split if we define storage as hosting, and sharing as transferring. However, that leads me to ask whether it might be clearer if we called data sharing "Data Transfer" instead. 

Pinging @Elisa-on-GitHub for their wisdom 😊

**Comment by Karvovskaya** [comment]
I think it's a good idea to use "Data Transfer" because sharing is too broad and can also refer to collaboration on the same dataset. I like the idea of splitting Storage in a seprate topic; I think it's quite self-contained. But I'll wait for @Elisa-on-GitHub to provide her wisdom!

**Comment by Elisa-on-GitHub** [comment]
Please don't wait for me _ever_ to provide my wisdom, I have very little! I think we have a Data Transfer heading somewhere else. We should have a look where this ended up and see if we should combine.

**Comment by chartgerink** [comment]
Don't sell yourself short, @Elisa-on-GitHub ❤️ 

It will be good to do another pass indeed. This should probably be a part of the work post-milestone. Feel free to assign yourself if you are planning on workign on this – otherwise I'll get around to it eventually 😊

**Comment by Karvovskaya** [comment]
There is a big overlap with **Data Services** part of the guide Data Life Cycle https://ubvu.github.io/open-handbook/guides/data-lifecycle.html
Maybe we can put these things together into concise topics to avoid duplication?

**Comment by Karvovskaya** [comment]
I think we can also make a connection to #213 because Data Transfer is also a part of another topic there - would be great to put all these pieces together into one topic instead of having overlapping subtopics.

**Comment by chartgerink** [comment]
It seems like the discussion in here has been resolved in the ongoing changes. I will close this issue and we can reopen in case there's any further developments/insights on this.
