### ISSUE TITLE
PURE manual (EN + NL)

### ISSUE THREAD

**Issue by chartgerink** [ubvu/open-handbook#208]
We are missing some links on the PURE manual, that we need to update. After the discussion in #170, I created this issue to focus on this specific issue.

- [ ] English
- [x] Dutch

**Comment by Jolien-S** [comment]
Current links to manuals:
Dutch: https://libguides.vu.nl/ld.php?content_id=32324060
English: I couldn't find this one in the LibGuide. Let's check with Dimitri.

**Comment by chartgerink** [comment]
Thanks @Jolien-S 🙌 I will update with the Dutch one. Could you keep us posted about whether you heard about the English one?

**Comment by chartgerink** [comment]
@Elisa-on-GitHub 🥲 

Will this do instead for now? https://libguides.vu.nl/pure-managing-publications/start

**Comment by Elisa-on-GitHub** [comment]
Yes, this works! Thanks, @chartgerink !
