### ISSUE TITLE
Adding fun in the mix?

### ISSUE THREAD

**Issue by chartgerink** [ubvu/open-handbook#21]
I know you created the O ❤️ S cardgame!

https://nlesc.github.io/open-loves-science/

Do we want to add a section on just fun stuff as well? This could be a part of a general resource pages as well, with a tag 😊 @Jolien-S @Karvovskaya @Elisa-on-GitHub @jhrudey

**Comment by Elisa-on-GitHub** [comment]
I think that's a great idea! Thanks for suggesting, Chris!

**Comment by jhrudey** [comment]
[heart]         Hrudey, E.J. (Jessica) reacted to your message:
________________________________
From: Chris Hartgerink ***@***.***>
Sent: Thursday, April 4, 2024 3:07:41 PM
To: ubvu/open-handbook ***@***.***>
Cc: Hrudey, E.J. (Jessica) ***@***.***>; Mention ***@***.***>
Subject: [ubvu/open-handbook] Adding fun in the mix? (Issue #21)


I know you created the O ❤️ S cardgame!

https://nlesc.github.io/open-loves-science/

Do we want to add a section on just fun stuff as well? This could be a part of a general resource pages as well, with a tag 😊 @Jolien-S<https://github.com/Jolien-S> @Karvovskaya<https://github.com/Karvovskaya> @Elisa-on-GitHub<https://github.com/Elisa-on-GitHub> @jhrudey<https://github.com/jhrudey>
