### ISSUE TITLE
Review trainings topic

### ISSUE THREAD

**Issue by Jolien-S** [ubvu/open-handbook#217]
Now the [trainings topic](https://rdm.vu.nl/topics/trainings.html) is in place, I think we should review it and adjust it a bit. The URLs now refer to different types of information. In some cases, it refers to course materials, whereas in others to an information page. I think we should provide different types of links for each training (although they will not be relevant for all of them), namely one with course materials and one with an information page/registration form/contact person.

We should also look into the values we have used for 'target audience'. It's inconsistent and not very informative ('everybody' 😅).

I will schedule a meeting with the training team to discuss this. I created this issue so that we don't forget to implement what comes out of that meeting.

**Comment by chartgerink** [comment]
Agreed – it felt rushed to merge for launch and a review would be good! Happy to do something like this during coworking for example.

**Comment by chartgerink** [comment]
I'm going to close this issue in favor of #193. This way we do not duplicate track this. If there's additional revision needs, they can surface in fixing that issue too, potentially.
