### ISSUE TITLE
Inclusion of the APH Quality handbook

### ISSUE THREAD

**Issue by Alex-van-der-Jagt** [ubvu/open-handbook#218]
During a lunch meeting today, one of the researchers informed me of another important resource to link to or incorporate in some way in the research handbook, namely https://aph-qualityhandbook.org/

A lot of the researchers in our section work with this. Maybe add this as a separate topic?

**Comment by chartgerink** [comment]
Hey @Alex-van-der-Jagt :wave: We [mention the APH in a few places](https://github.com/search?q=repo%3Aubvu%2Fopen-handbook+aph-quality&type=code) – I am not sure I immediately see the relevance as a topic itself. 

But maybe @Elisa-on-GitHub @Jolien-S have a good take on this?

In any case, thanks for thinking of the Research Support Handbook and taking the effort to open up this issue <3

**Comment by chartgerink** [comment]
It seems like this is not being taken up, so I will close this until there's more activity. 👍
