### ISSUE TITLE
Add videos from VU RDS pages

### ISSUE THREAD

**Issue by Karvovskaya** [ubvu/open-handbook#219]
Few years ago, VU RDM colleagues contributed to short animations explaining RDM principles and tools available.
These videos should be added to the handbook

1. Add here https://rdm.vu.nl/topics/research-data-management.html RDM: How, What and Why? https://www.youtube.com/watch?v=Dw_bwegR76I 
2. Should be part of this guide https://rdm.vu.nl/guides/data-lifecycle.html but this guide first needs to become topics, see #216 RDM: Tools and Storage https://www.youtube.com/watch?v=-AaSNZzL_KQ
3.  Yoda should be part of #92 How to: Yoda
https://www.youtube.com/watch?v=N67v2v62Qn0&t=1s

**Comment by chartgerink** [comment]
Thanks @Karvovskaya 🙌 I opened a PR in #229, and given that you already mentioned the video for Yoda in its own issue, I think we can move forward to include these videos now and refine the work based on the other outstanding issues. 👍
