### ISSUE TITLE
Clean-up notes to self in "Register your processing activities" and "data assets"

### ISSUE THREAD

**Issue by jhrudey** [ubvu/open-handbook#25]
There are a couple of notes we've put for ourselves in these two sections about linking to other pages of interest. With regards to "Register your processing activities" the hyperlink in the title is just confusing and should  be removed. The note to ourselves to include a hyperlink to a GDPR page within the text is fine, but we don't have a page yet  nor will we any time soon, so shall we temporarily link to a general page on the GDPR until then, like this page https://gdpr-info.eu/?

**Comment by Elisa-on-GitHub** [comment]
This is related to issue #32 and PR #37
