### ISSUE TITLE
Include Yoda information page in handbook

### ISSUE THREAD

**Issue by Jolien-S** [ubvu/open-handbook#252]
Include the current information page about [Yoda](https://yoda.vu.nl/site/) in the handbook.

**Comment by Elisa-on-GitHub** [comment]
@Jolien-S I'm keeping this open for now, this is a real issue, i.e. not a test issue, right?

**Comment by peer35** [comment]
Also see #92

**Comment by Jolien-S** [comment]
Yes, it's a real issue, but I now see that there was a Yoda issues already, as @peer35 indicated. So we could also close this one and continue with #92.

**Comment by chartgerink** [comment]
Addressed in #270.
