### ISSUE TITLE
Verify table description length

### ISSUE THREAD

**Issue by chartgerink** [ubvu/open-handbook#32]
> [https://libguides.vu.nl/rdm/dmp?#s-lg-box-wrapper-15125649 > Elisa has another look at the table description, because it is quite brief]

This comment remains in the chapter. @Elisa-on-GitHub would you mind taking another look and verifying what needs to be changed (if anything) to resolve this item?

You can find the relevant bit on [line 85 of the DMP chapter](https://github.com/ubvu/open-handbook/blob/3f927bbca6193eff14dbb45aa79dd022bf0173bb/chapters/data-management-plan.qmd#L85).

**Comment by Elisa-on-GitHub** [comment]
Thank you Chris! I see what I meant and I'm working on it!
