### ISSUE TITLE
Manual including repo 'etiquette'

### ISSUE THREAD

**Issue by Elisa-on-GitHub** [ubvu/open-handbook#39]
In our manual for ourselves, it would also be good to write down our 'etiquette', by which I mean the ways of working that we've discussed and agreed on. For example, Jolien and I were merging PRs two weeks ago, and we realised we didn't know if we could delete the branch of which the patch was merged. Both of us vaguely remembered discussing it in one of the meetings, but we didn't know for sure anymore.
If the group of admins grows, this sort of thing, and other 'etiquette' rules is good to write down as part of the manual.

Something else that I would lke is to understand a little bit more about what exactly is netlify, what does it do and how does it work? I've come across Netlify before, e.g. in the Turing Way, but this is also good to write down in the manual.

**Comment by chartgerink** [comment]
Great point @Elisa-on-GitHub! We can use this thread to start documenting some of what should go in there. I'll try to answer your questions 👇 

## Deleting branches

After merging Pull Requests, it is expected to clean up the branch by deleting it. We enable auto deletion upon merging, but if that for some reason does not happen, please go ahead and "Delete branch"

## Netlify

Netlify is a hosting service, where the files for the website live. This means that even though we create the website on GitHub, Netlify is where the website is hosted. When GitHub is down, the website should be unaffected.

**Comment by chartgerink** [comment]
PR merging etiquette is implicit at the moment, as raised by @jhrudey in #42. I seem to recall that we agreed that at least one editor needs to approve the changes, but haven't discussed who merges. Shall we say that any editor can merge after a PR is approved and has no pending requested changes?
