### ISSUE TITLE
Suggestions for the landing page

### ISSUE THREAD

**Issue by Karvovskaya** [ubvu/open-handbook#73]
These are joint suggestions by Lena, Jessica, Jolien and Elisa

- [x] Clicking on VU logo should probably lead to the official VU website?

- [x] Above the BENEFITS, next to link to topics, and a  link to pathways 

- [x] We think here more contextualisation is needed: "VU has plenty of resources already. Why use this one?" A suggestion "there are so many guidelines on RDM and Open Science. Why this one?"

- [x] Add BENEFIT: bring together fragmented information - maybe **synergistic** (never used this word before)

**Comment by chartgerink** [comment]
Thanks for the suggestions!

We can definitely make these changes if you wish. Here are some thoughts

- It is uncommon for navigation to lead away from the page itself and to a parent page. Happy to do it nonetheless but it is not a standard practice (in web development navigation bars should only contain relative paths, is the heuristic).
- No comments on the pathways link 😊 
- Good copy is clear and concise - including an acronym may not be the best choice for that. I am happy to contextualise, and I am not sure whether this is the way to go. Your suggestion also generalises it to resources beyond the VU - do we want to do that?
- It will cause an uneven number so preferably I'd add TWO benefits 😄 Also, is there an icon that fits for this? I use https://heroicons.com/ for thesse

Happy to make any changes you recommend in any case 👍

**Comment by Karvovskaya** [comment]
Let's not navigate to another page unless VU UX colleagues advise this.
We probably need to think more about contextualising and benefits - at least I can't recall the full logic at the moment. Indeed, staying in the scope of the VU is important. I think we just wanted to be more specific that these are resources somehow related to Research Data Management and Open Science

**Comment by chartgerink** [comment]
Some additional remarks for the landing page from VU UX:

## Menu

The home button can actually be removed from the menu. In fact, the logo right next to it also leads to the home page. In addition, the home page does not provide references that cannot be reached through the other buttons in the menu. 

Also, I recommend changing the order of the menu to: Topics, Pathways, Blog, Contribute. This puts the “primary” pages first.

## Homepage:

Change the H1/H2 text -> make sure that in the title it is immediately clear what the website is for and what people can find there (e.g.: the handbook on all things research management/quality information on research practices/Research Support Handbook: your VU community-curated guide, etc. Below the title you can add a short paragraph (max 100 words) explaining what the handbook is and how the website works.d

---

I have blocked some time to resolve all these points tomorrow evening.
