### ISSUE TITLE
Connecting to discipline specific resources

### ISSUE THREAD

**Issue by Karvovskaya** [ubvu/open-handbook#75]
Maybe a good test case to see how we go from central resources to specific pages of faculties and departments. There is this wonderful [handbook ](https://marbarrantescepas.github.io/OS-neuroscience/) by neuroscience colleagues who are interested in joining forces with us. How can we best interconnect the two while not making it confusing.
Sorry not very specific issue yet

**Comment by Karvovskaya** [comment]
There is also another VU git page being developed; this time for computer sciences. We could try to see how to connect there

**Comment by chartgerink** [comment]
@Karvovskaya - would you like to have a topic on community handbooks that could provide links to the different ones at the VU?

**Comment by chartgerink** [comment]
This topic is now stale and will be closed until further needs arise 👍
